/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppendixRouteImport } from './routes/appendix'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WebhooksSummarizeCaseRouteImport } from './routes/webhooks/summarize-case'
import { Route as WebhooksSendApprovedRouteImport } from './routes/webhooks/send-approved'
import { Route as WebhooksPartnerSyncRouteImport } from './routes/webhooks/partner-sync'
import { Route as WebhooksPartnerReplyRouteImport } from './routes/webhooks/partner-reply'
import { Route as WebhooksOpsSnapshotRouteImport } from './routes/webhooks/ops-snapshot'
import { Route as WebhooksMailgunEventsRouteImport } from './routes/webhooks/mailgun-events'
import { Route as WebhooksLeadIntakeRouteImport } from './routes/webhooks/lead-intake'
import { Route as WebhooksGmailSyncRouteImport } from './routes/webhooks/gmail-sync'
import { Route as WebhooksGeneratePartnerDraftRouteImport } from './routes/webhooks/generate-partner-draft'
import { Route as WebhooksGenerateDraftRouteImport } from './routes/webhooks/generate-draft'
import { Route as WebhooksConversationLogRouteImport } from './routes/webhooks/conversation-log'
import { Route as WebhooksCaseReplyRouteImport } from './routes/webhooks/case-reply'
import { Route as WebhooksCaseCreateRouteImport } from './routes/webhooks/case-create'
import { Route as WebhooksCaseActionRouteImport } from './routes/webhooks/case-action'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as SecureFormTokenRouteImport } from './routes/secure-form.$token'
import { Route as ReviewCaseIdRouteImport } from './routes/review.$caseId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AdminTrackingLinksRouteImport } from './routes/admin.tracking-links'
import { Route as AdminSecureKeysRouteImport } from './routes/admin.secure-keys'
import { Route as AdminSecureInboxRouteImport } from './routes/admin.secure-inbox'
import { Route as AdminChangeRequestsRouteImport } from './routes/admin.change-requests'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppendixRoute = AppendixRouteImport.update({
  id: '/appendix',
  path: '/appendix',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WebhooksSummarizeCaseRoute = WebhooksSummarizeCaseRouteImport.update({
  id: '/webhooks/summarize-case',
  path: '/webhooks/summarize-case',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksSendApprovedRoute = WebhooksSendApprovedRouteImport.update({
  id: '/webhooks/send-approved',
  path: '/webhooks/send-approved',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksPartnerSyncRoute = WebhooksPartnerSyncRouteImport.update({
  id: '/webhooks/partner-sync',
  path: '/webhooks/partner-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksPartnerReplyRoute = WebhooksPartnerReplyRouteImport.update({
  id: '/webhooks/partner-reply',
  path: '/webhooks/partner-reply',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksOpsSnapshotRoute = WebhooksOpsSnapshotRouteImport.update({
  id: '/webhooks/ops-snapshot',
  path: '/webhooks/ops-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksMailgunEventsRoute = WebhooksMailgunEventsRouteImport.update({
  id: '/webhooks/mailgun-events',
  path: '/webhooks/mailgun-events',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksLeadIntakeRoute = WebhooksLeadIntakeRouteImport.update({
  id: '/webhooks/lead-intake',
  path: '/webhooks/lead-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksGmailSyncRoute = WebhooksGmailSyncRouteImport.update({
  id: '/webhooks/gmail-sync',
  path: '/webhooks/gmail-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksGeneratePartnerDraftRoute =
  WebhooksGeneratePartnerDraftRouteImport.update({
    id: '/webhooks/generate-partner-draft',
    path: '/webhooks/generate-partner-draft',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebhooksGenerateDraftRoute = WebhooksGenerateDraftRouteImport.update({
  id: '/webhooks/generate-draft',
  path: '/webhooks/generate-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksConversationLogRoute = WebhooksConversationLogRouteImport.update({
  id: '/webhooks/conversation-log',
  path: '/webhooks/conversation-log',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksCaseReplyRoute = WebhooksCaseReplyRouteImport.update({
  id: '/webhooks/case-reply',
  path: '/webhooks/case-reply',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksCaseCreateRoute = WebhooksCaseCreateRouteImport.update({
  id: '/webhooks/case-create',
  path: '/webhooks/case-create',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksCaseActionRoute = WebhooksCaseActionRouteImport.update({
  id: '/webhooks/case-action',
  path: '/webhooks/case-action',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SecureFormTokenRoute = SecureFormTokenRouteImport.update({
  id: '/secure-form/$token',
  path: '/secure-form/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewCaseIdRoute = ReviewCaseIdRouteImport.update({
  id: '/review/$caseId',
  path: '/review/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrackingLinksRoute = AdminTrackingLinksRouteImport.update({
  id: '/tracking-links',
  path: '/tracking-links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecureKeysRoute = AdminSecureKeysRouteImport.update({
  id: '/secure-keys',
  path: '/secure-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecureInboxRoute = AdminSecureInboxRouteImport.update({
  id: '/secure-inbox',
  path: '/secure-inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChangeRequestsRoute = AdminChangeRequestsRouteImport.update({
  id: '/change-requests',
  path: '/change-requests',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/appendix': typeof AppendixRoute
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/change-requests': typeof AdminChangeRequestsRoute
  '/admin/secure-inbox': typeof AdminSecureInboxRoute
  '/admin/secure-keys': typeof AdminSecureKeysRoute
  '/admin/tracking-links': typeof AdminTrackingLinksRoute
  '/api/health': typeof ApiHealthRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/review/$caseId': typeof ReviewCaseIdRoute
  '/secure-form/$token': typeof SecureFormTokenRoute
  '/track/$token': typeof TrackTokenRoute
  '/webhooks/case-action': typeof WebhooksCaseActionRoute
  '/webhooks/case-create': typeof WebhooksCaseCreateRoute
  '/webhooks/case-reply': typeof WebhooksCaseReplyRoute
  '/webhooks/conversation-log': typeof WebhooksConversationLogRoute
  '/webhooks/generate-draft': typeof WebhooksGenerateDraftRoute
  '/webhooks/generate-partner-draft': typeof WebhooksGeneratePartnerDraftRoute
  '/webhooks/gmail-sync': typeof WebhooksGmailSyncRoute
  '/webhooks/lead-intake': typeof WebhooksLeadIntakeRoute
  '/webhooks/mailgun-events': typeof WebhooksMailgunEventsRoute
  '/webhooks/ops-snapshot': typeof WebhooksOpsSnapshotRoute
  '/webhooks/partner-reply': typeof WebhooksPartnerReplyRoute
  '/webhooks/partner-sync': typeof WebhooksPartnerSyncRoute
  '/webhooks/send-approved': typeof WebhooksSendApprovedRoute
  '/webhooks/summarize-case': typeof WebhooksSummarizeCaseRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appendix': typeof AppendixRoute
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/change-requests': typeof AdminChangeRequestsRoute
  '/admin/secure-inbox': typeof AdminSecureInboxRoute
  '/admin/secure-keys': typeof AdminSecureKeysRoute
  '/admin/tracking-links': typeof AdminTrackingLinksRoute
  '/api/health': typeof ApiHealthRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/review/$caseId': typeof ReviewCaseIdRoute
  '/secure-form/$token': typeof SecureFormTokenRoute
  '/track/$token': typeof TrackTokenRoute
  '/webhooks/case-action': typeof WebhooksCaseActionRoute
  '/webhooks/case-create': typeof WebhooksCaseCreateRoute
  '/webhooks/case-reply': typeof WebhooksCaseReplyRoute
  '/webhooks/conversation-log': typeof WebhooksConversationLogRoute
  '/webhooks/generate-draft': typeof WebhooksGenerateDraftRoute
  '/webhooks/generate-partner-draft': typeof WebhooksGeneratePartnerDraftRoute
  '/webhooks/gmail-sync': typeof WebhooksGmailSyncRoute
  '/webhooks/lead-intake': typeof WebhooksLeadIntakeRoute
  '/webhooks/mailgun-events': typeof WebhooksMailgunEventsRoute
  '/webhooks/ops-snapshot': typeof WebhooksOpsSnapshotRoute
  '/webhooks/partner-reply': typeof WebhooksPartnerReplyRoute
  '/webhooks/partner-sync': typeof WebhooksPartnerSyncRoute
  '/webhooks/send-approved': typeof WebhooksSendApprovedRoute
  '/webhooks/summarize-case': typeof WebhooksSummarizeCaseRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/appendix': typeof AppendixRoute
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/change-requests': typeof AdminChangeRequestsRoute
  '/admin/secure-inbox': typeof AdminSecureInboxRoute
  '/admin/secure-keys': typeof AdminSecureKeysRoute
  '/admin/tracking-links': typeof AdminTrackingLinksRoute
  '/api/health': typeof ApiHealthRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/review/$caseId': typeof ReviewCaseIdRoute
  '/secure-form/$token': typeof SecureFormTokenRoute
  '/track/$token': typeof TrackTokenRoute
  '/webhooks/case-action': typeof WebhooksCaseActionRoute
  '/webhooks/case-create': typeof WebhooksCaseCreateRoute
  '/webhooks/case-reply': typeof WebhooksCaseReplyRoute
  '/webhooks/conversation-log': typeof WebhooksConversationLogRoute
  '/webhooks/generate-draft': typeof WebhooksGenerateDraftRoute
  '/webhooks/generate-partner-draft': typeof WebhooksGeneratePartnerDraftRoute
  '/webhooks/gmail-sync': typeof WebhooksGmailSyncRoute
  '/webhooks/lead-intake': typeof WebhooksLeadIntakeRoute
  '/webhooks/mailgun-events': typeof WebhooksMailgunEventsRoute
  '/webhooks/ops-snapshot': typeof WebhooksOpsSnapshotRoute
  '/webhooks/partner-reply': typeof WebhooksPartnerReplyRoute
  '/webhooks/partner-sync': typeof WebhooksPartnerSyncRoute
  '/webhooks/send-approved': typeof WebhooksSendApprovedRoute
  '/webhooks/summarize-case': typeof WebhooksSummarizeCaseRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/appendix'
    | '/dashboard'
    | '/drafts'
    | '/leads'
    | '/login'
    | '/reset-password'
    | '/unsubscribe'
    | '/admin/change-requests'
    | '/admin/secure-inbox'
    | '/admin/secure-keys'
    | '/admin/tracking-links'
    | '/api/health'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/jobs/$jobId'
    | '/review/$caseId'
    | '/secure-form/$token'
    | '/track/$token'
    | '/webhooks/case-action'
    | '/webhooks/case-create'
    | '/webhooks/case-reply'
    | '/webhooks/conversation-log'
    | '/webhooks/generate-draft'
    | '/webhooks/generate-partner-draft'
    | '/webhooks/gmail-sync'
    | '/webhooks/lead-intake'
    | '/webhooks/mailgun-events'
    | '/webhooks/ops-snapshot'
    | '/webhooks/partner-reply'
    | '/webhooks/partner-sync'
    | '/webhooks/send-approved'
    | '/webhooks/summarize-case'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appendix'
    | '/dashboard'
    | '/drafts'
    | '/leads'
    | '/login'
    | '/reset-password'
    | '/unsubscribe'
    | '/admin/change-requests'
    | '/admin/secure-inbox'
    | '/admin/secure-keys'
    | '/admin/tracking-links'
    | '/api/health'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/jobs/$jobId'
    | '/review/$caseId'
    | '/secure-form/$token'
    | '/track/$token'
    | '/webhooks/case-action'
    | '/webhooks/case-create'
    | '/webhooks/case-reply'
    | '/webhooks/conversation-log'
    | '/webhooks/generate-draft'
    | '/webhooks/generate-partner-draft'
    | '/webhooks/gmail-sync'
    | '/webhooks/lead-intake'
    | '/webhooks/mailgun-events'
    | '/webhooks/ops-snapshot'
    | '/webhooks/partner-reply'
    | '/webhooks/partner-sync'
    | '/webhooks/send-approved'
    | '/webhooks/summarize-case'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/appendix'
    | '/dashboard'
    | '/drafts'
    | '/leads'
    | '/login'
    | '/reset-password'
    | '/unsubscribe'
    | '/admin/change-requests'
    | '/admin/secure-inbox'
    | '/admin/secure-keys'
    | '/admin/tracking-links'
    | '/api/health'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/jobs/$jobId'
    | '/review/$caseId'
    | '/secure-form/$token'
    | '/track/$token'
    | '/webhooks/case-action'
    | '/webhooks/case-create'
    | '/webhooks/case-reply'
    | '/webhooks/conversation-log'
    | '/webhooks/generate-draft'
    | '/webhooks/generate-partner-draft'
    | '/webhooks/gmail-sync'
    | '/webhooks/lead-intake'
    | '/webhooks/mailgun-events'
    | '/webhooks/ops-snapshot'
    | '/webhooks/partner-reply'
    | '/webhooks/partner-sync'
    | '/webhooks/send-approved'
    | '/webhooks/summarize-case'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppendixRoute: typeof AppendixRoute
  DashboardRoute: typeof DashboardRoute
  DraftsRoute: typeof DraftsRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiHealthRoute: typeof ApiHealthRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ReviewCaseIdRoute: typeof ReviewCaseIdRoute
  SecureFormTokenRoute: typeof SecureFormTokenRoute
  TrackTokenRoute: typeof TrackTokenRoute
  WebhooksCaseActionRoute: typeof WebhooksCaseActionRoute
  WebhooksCaseCreateRoute: typeof WebhooksCaseCreateRoute
  WebhooksCaseReplyRoute: typeof WebhooksCaseReplyRoute
  WebhooksConversationLogRoute: typeof WebhooksConversationLogRoute
  WebhooksGenerateDraftRoute: typeof WebhooksGenerateDraftRoute
  WebhooksGeneratePartnerDraftRoute: typeof WebhooksGeneratePartnerDraftRoute
  WebhooksGmailSyncRoute: typeof WebhooksGmailSyncRoute
  WebhooksLeadIntakeRoute: typeof WebhooksLeadIntakeRoute
  WebhooksMailgunEventsRoute: typeof WebhooksMailgunEventsRoute
  WebhooksOpsSnapshotRoute: typeof WebhooksOpsSnapshotRoute
  WebhooksPartnerReplyRoute: typeof WebhooksPartnerReplyRoute
  WebhooksPartnerSyncRoute: typeof WebhooksPartnerSyncRoute
  WebhooksSendApprovedRoute: typeof WebhooksSendApprovedRoute
  WebhooksSummarizeCaseRoute: typeof WebhooksSummarizeCaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appendix': {
      id: '/appendix'
      path: '/appendix'
      fullPath: '/appendix'
      preLoaderRoute: typeof AppendixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/webhooks/summarize-case': {
      id: '/webhooks/summarize-case'
      path: '/webhooks/summarize-case'
      fullPath: '/webhooks/summarize-case'
      preLoaderRoute: typeof WebhooksSummarizeCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/send-approved': {
      id: '/webhooks/send-approved'
      path: '/webhooks/send-approved'
      fullPath: '/webhooks/send-approved'
      preLoaderRoute: typeof WebhooksSendApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/partner-sync': {
      id: '/webhooks/partner-sync'
      path: '/webhooks/partner-sync'
      fullPath: '/webhooks/partner-sync'
      preLoaderRoute: typeof WebhooksPartnerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/partner-reply': {
      id: '/webhooks/partner-reply'
      path: '/webhooks/partner-reply'
      fullPath: '/webhooks/partner-reply'
      preLoaderRoute: typeof WebhooksPartnerReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/ops-snapshot': {
      id: '/webhooks/ops-snapshot'
      path: '/webhooks/ops-snapshot'
      fullPath: '/webhooks/ops-snapshot'
      preLoaderRoute: typeof WebhooksOpsSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/mailgun-events': {
      id: '/webhooks/mailgun-events'
      path: '/webhooks/mailgun-events'
      fullPath: '/webhooks/mailgun-events'
      preLoaderRoute: typeof WebhooksMailgunEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/lead-intake': {
      id: '/webhooks/lead-intake'
      path: '/webhooks/lead-intake'
      fullPath: '/webhooks/lead-intake'
      preLoaderRoute: typeof WebhooksLeadIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/gmail-sync': {
      id: '/webhooks/gmail-sync'
      path: '/webhooks/gmail-sync'
      fullPath: '/webhooks/gmail-sync'
      preLoaderRoute: typeof WebhooksGmailSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/generate-partner-draft': {
      id: '/webhooks/generate-partner-draft'
      path: '/webhooks/generate-partner-draft'
      fullPath: '/webhooks/generate-partner-draft'
      preLoaderRoute: typeof WebhooksGeneratePartnerDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/generate-draft': {
      id: '/webhooks/generate-draft'
      path: '/webhooks/generate-draft'
      fullPath: '/webhooks/generate-draft'
      preLoaderRoute: typeof WebhooksGenerateDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/conversation-log': {
      id: '/webhooks/conversation-log'
      path: '/webhooks/conversation-log'
      fullPath: '/webhooks/conversation-log'
      preLoaderRoute: typeof WebhooksConversationLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/case-reply': {
      id: '/webhooks/case-reply'
      path: '/webhooks/case-reply'
      fullPath: '/webhooks/case-reply'
      preLoaderRoute: typeof WebhooksCaseReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/case-create': {
      id: '/webhooks/case-create'
      path: '/webhooks/case-create'
      fullPath: '/webhooks/case-create'
      preLoaderRoute: typeof WebhooksCaseCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/case-action': {
      id: '/webhooks/case-action'
      path: '/webhooks/case-action'
      fullPath: '/webhooks/case-action'
      preLoaderRoute: typeof WebhooksCaseActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secure-form/$token': {
      id: '/secure-form/$token'
      path: '/secure-form/$token'
      fullPath: '/secure-form/$token'
      preLoaderRoute: typeof SecureFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$caseId': {
      id: '/review/$caseId'
      path: '/review/$caseId'
      fullPath: '/review/$caseId'
      preLoaderRoute: typeof ReviewCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tracking-links': {
      id: '/admin/tracking-links'
      path: '/tracking-links'
      fullPath: '/admin/tracking-links'
      preLoaderRoute: typeof AdminTrackingLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/secure-keys': {
      id: '/admin/secure-keys'
      path: '/secure-keys'
      fullPath: '/admin/secure-keys'
      preLoaderRoute: typeof AdminSecureKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/secure-inbox': {
      id: '/admin/secure-inbox'
      path: '/secure-inbox'
      fullPath: '/admin/secure-inbox'
      preLoaderRoute: typeof AdminSecureInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/change-requests': {
      id: '/admin/change-requests'
      path: '/change-requests'
      fullPath: '/admin/change-requests'
      preLoaderRoute: typeof AdminChangeRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChangeRequestsRoute: typeof AdminChangeRequestsRoute
  AdminSecureInboxRoute: typeof AdminSecureInboxRoute
  AdminSecureKeysRoute: typeof AdminSecureKeysRoute
  AdminTrackingLinksRoute: typeof AdminTrackingLinksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChangeRequestsRoute: AdminChangeRequestsRoute,
  AdminSecureInboxRoute: AdminSecureInboxRoute,
  AdminSecureKeysRoute: AdminSecureKeysRoute,
  AdminTrackingLinksRoute: AdminTrackingLinksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppendixRoute: AppendixRoute,
  DashboardRoute: DashboardRoute,
  DraftsRoute: DraftsRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiHealthRoute: ApiHealthRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteTokenRoute: InviteTokenRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ReviewCaseIdRoute: ReviewCaseIdRoute,
  SecureFormTokenRoute: SecureFormTokenRoute,
  TrackTokenRoute: TrackTokenRoute,
  WebhooksCaseActionRoute: WebhooksCaseActionRoute,
  WebhooksCaseCreateRoute: WebhooksCaseCreateRoute,
  WebhooksCaseReplyRoute: WebhooksCaseReplyRoute,
  WebhooksConversationLogRoute: WebhooksConversationLogRoute,
  WebhooksGenerateDraftRoute: WebhooksGenerateDraftRoute,
  WebhooksGeneratePartnerDraftRoute: WebhooksGeneratePartnerDraftRoute,
  WebhooksGmailSyncRoute: WebhooksGmailSyncRoute,
  WebhooksLeadIntakeRoute: WebhooksLeadIntakeRoute,
  WebhooksMailgunEventsRoute: WebhooksMailgunEventsRoute,
  WebhooksOpsSnapshotRoute: WebhooksOpsSnapshotRoute,
  WebhooksPartnerReplyRoute: WebhooksPartnerReplyRoute,
  WebhooksPartnerSyncRoute: WebhooksPartnerSyncRoute,
  WebhooksSendApprovedRoute: WebhooksSendApprovedRoute,
  WebhooksSummarizeCaseRoute: WebhooksSummarizeCaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
