// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import { describeSupabaseToken, getSupabaseProjectHost } from "./auth-diagnostics";
import type { Database } from "./types";

type AuthValidationSource =
  | "publishable_get_user"
  | "publishable_rest_user"
  | "service_role_rest_user";

type AuthValidationAttempt = {
  source: AuthValidationSource;
  ok: boolean;
  status: number | null;
  errorDetail: string | null;
};

type AuthenticatedUser = {
  id: string;
  email: string | null;
};

const MAX_AUTH_DETAIL_HEADER_LENGTH = 48;

function logUnauthorized(reason: string, details: Record<string, unknown>) {
  console.error("[requireSupabaseAuth] unauthorized", {
    reason,
    ...details,
  });
}

function getSafeErrorDetail(error: unknown) {
  if (error instanceof Error) return error.message.slice(0, 180);
  if (typeof error === "string") return error.slice(0, 180);
  return null;
}

function getAuthAttemptHeaderValue(attempts: AuthValidationAttempt[]) {
  if (attempts.length === 0) return "none";
  return attempts
    .map((attempt) => {
      const status = attempt.status == null ? "no_status" : String(attempt.status);
      const detail = attempt.errorDetail
        ? attempt.errorDetail
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "_")
            .slice(0, MAX_AUTH_DETAIL_HEADER_LENGTH)
        : "none";
      return `${attempt.source}:${status}:${detail}`;
    })
    .join(",");
}

function createUnauthorizedResponse(
  message: string,
  reason: string,
  input: {
    projectHost: string | null;
    clientProjectHost?: string | null;
    clientSessionPresent?: string | null;
    clientAccessTokenPresent?: string | null;
    tokenShape?: string | null;
    authDetail?: string | null;
    validationSource?: string | null;
  },
) {
  return new Response(message, {
    status: 401,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "x-mgt-auth-reason": reason,
      "x-mgt-supabase-project-host": input.projectHost ?? "unknown",
      "x-mgt-token-shape": input.tokenShape ?? "unknown",
      "x-mgt-client-session-present": input.clientSessionPresent ?? "unknown",
      "x-mgt-client-access-token-present": input.clientAccessTokenPresent ?? "unknown",
      "x-mgt-client-supabase-project-host": input.clientProjectHost ?? "unknown",
      "x-mgt-auth-detail": input.authDetail ?? "unknown",
      "x-mgt-auth-validation-source": input.validationSource ?? "unknown",
    },
  });
}

function createAuthContext(input: {
  supabase: ReturnType<typeof createClient<Database>>;
  userId: string;
  email?: string | null;
  claims?: Record<string, unknown> | null;
}) {
  return {
    supabase: input.supabase,
    userId: input.userId,
    claims: {
      ...(input.claims ?? {}),
      sub: input.userId,
      email: input.email ?? null,
    },
  };
}

async function validateUserWithRest(input: {
  source: Extract<AuthValidationSource, "publishable_rest_user" | "service_role_rest_user">;
  supabaseUrl: string;
  apiKey: string;
  token: string;
}): Promise<{ attempt: AuthValidationAttempt; user: AuthenticatedUser | null }> {
  try {
    const userUrl = new URL("/auth/v1/user", input.supabaseUrl);
    const response = await fetch(userUrl, {
      method: "GET",
      headers: {
        apikey: input.apiKey,
        Authorization: `Bearer ${input.token}`,
      },
    });

    const responseText = await response.text();
    let payload: unknown = responseText || null;
    try {
      payload = responseText ? JSON.parse(responseText) : null;
    } catch {
      payload = responseText || null;
    }

    const user =
      payload && typeof payload === "object" && "id" in payload && typeof payload.id === "string"
        ? {
            id: payload.id,
            email: "email" in payload && typeof payload.email === "string" ? payload.email : null,
          }
        : null;

    if (response.ok && user?.id) {
      return {
        attempt: {
          source: input.source,
          ok: true,
          status: response.status,
          errorDetail: null,
        },
        user,
      };
    }

    if (response.ok && !user?.id) {
      return {
        attempt: {
          source: input.source,
          ok: false,
          status: response.status,
          errorDetail: "ok_without_user_id",
        },
        user: null,
      };
    }

    const payloadError =
      payload && typeof payload === "object"
        ? [
            "code" in payload && typeof payload.code === "string" ? payload.code : null,
            "error" in payload && typeof payload.error === "string" ? payload.error : null,
            "msg" in payload && typeof payload.msg === "string" ? payload.msg : null,
            "message" in payload && typeof payload.message === "string" ? payload.message : null,
            "error_description" in payload && typeof payload.error_description === "string"
              ? payload.error_description
              : null,
          ]
            .filter(Boolean)
            .join(": ")
        : typeof payload === "string"
          ? payload
          : null;

    return {
      attempt: {
        source: input.source,
        ok: false,
        status: response.status,
        errorDetail: (payloadError || response.statusText || "rest_user_lookup_failed").slice(
          0,
          180,
        ),
      },
      user: null,
    };
  } catch (error) {
    return {
      attempt: {
        source: input.source,
        ok: false,
        status: null,
        errorDetail: getSafeErrorDetail(error) ?? "rest_user_lookup_failed",
      },
      user: null,
    };
  }
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;
    const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
    const projectHost = getSupabaseProjectHost(SUPABASE_URL);

    console.info("[requireSupabaseAuth] config", {
      hasSupabaseUrl: !!SUPABASE_URL,
      hasSupabasePublishableKey: !!SUPABASE_PUBLISHABLE_KEY,
      hasSupabaseServiceRoleKey: !!SUPABASE_SERVICE_ROLE_KEY,
      authApiKeyMode: SUPABASE_PUBLISHABLE_KEY
        ? "publishable"
        : SUPABASE_SERVICE_ROLE_KEY
          ? "service_role_only"
          : "missing",
      projectHost,
    });

    if (!SUPABASE_URL || (!SUPABASE_PUBLISHABLE_KEY && !SUPABASE_SERVICE_ROLE_KEY)) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY && !SUPABASE_SERVICE_ROLE_KEY
          ? ["SUPABASE_PUBLISHABLE_KEY or SUPABASE_SERVICE_ROLE_KEY"]
          : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Response(message, { status: 500 });
    }

    const request = getRequest();
    const clientProjectHost = request?.headers?.get("x-mgt-client-supabase-project-host");
    const clientSessionPresent = request?.headers?.get("x-mgt-client-session-present");
    const clientAccessTokenPresent = request?.headers?.get("x-mgt-client-access-token-present");

    if (!request?.headers) {
      logUnauthorized("no_request_headers", { projectHost });
      throw createUnauthorizedResponse(
        "Unauthorized: No request headers available",
        "no_request_headers",
        { projectHost, clientProjectHost, clientSessionPresent, clientAccessTokenPresent },
      );
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      logUnauthorized("no_authorization_header", { projectHost });
      throw createUnauthorizedResponse(
        "Unauthorized: No authorization header provided",
        "no_authorization_header",
        { projectHost, clientProjectHost, clientSessionPresent, clientAccessTokenPresent },
      );
    }

    if (!authHeader.startsWith("Bearer ")) {
      logUnauthorized("authorization_not_bearer", { projectHost });
      throw createUnauthorizedResponse(
        "Unauthorized: Only Bearer tokens are supported",
        "authorization_not_bearer",
        { projectHost, clientProjectHost, clientSessionPresent, clientAccessTokenPresent },
      );
    }

    const token = authHeader.replace("Bearer ", "");
    const tokenDiagnostics = describeSupabaseToken(token);
    const authDiagnostics = {
      projectHost,
      clientProjectHost,
      clientSessionPresent,
      clientAccessTokenPresent,
      tokenExists: tokenDiagnostics.exists,
      tokenLength: tokenDiagnostics.length,
      tokenHasThreeSegments: tokenDiagnostics.hasThreeSegments,
      tokenPrefixType: tokenDiagnostics.prefixType,
      tokenShape: tokenDiagnostics.headerValue,
    };

    console.info("[requireSupabaseAuth] request auth diagnostics", authDiagnostics);

    if (!token) {
      logUnauthorized("no_token", authDiagnostics);
      throw createUnauthorizedResponse("Unauthorized: No token provided", "no_token", {
        projectHost,
        clientProjectHost,
        clientSessionPresent,
        clientAccessTokenPresent,
        tokenShape: tokenDiagnostics.headerValue,
      });
    }

    if (clientProjectHost && projectHost && clientProjectHost !== projectHost) {
      console.warn("[requireSupabaseAuth] auth diagnostic", {
        reason: "project_host_mismatch",
        clientProjectHost,
        projectHost,
      });
    }

    if (!tokenDiagnostics.isLikelyJwt) {
      logUnauthorized("invalid_token_shape", authDiagnostics);
      throw createUnauthorizedResponse(
        "Unauthorized: Invalid Supabase session token. Please sign out and sign in again.",
        "invalid_token_shape",
        {
          projectHost,
          clientProjectHost,
          clientSessionPresent,
          clientAccessTokenPresent,
          tokenShape: tokenDiagnostics.headerValue,
        },
      );
    }

    const authClientOptions = {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    } as const;

    const authApiKey = SUPABASE_PUBLISHABLE_KEY ?? SUPABASE_SERVICE_ROLE_KEY;
    const supabase = createClient<Database>(SUPABASE_URL!, authApiKey!, authClientOptions);

    const validationAttempts: AuthValidationAttempt[] = [];
    let validatedUser: AuthenticatedUser | null = null;
    let validationSource: AuthValidationSource | null = null;

    if (SUPABASE_PUBLISHABLE_KEY) {
      try {
        const { data, error } = await supabase.auth.getUser(token);
        const user =
          data.user?.id != null
            ? {
                id: data.user.id,
                email: data.user.email ?? null,
              }
            : null;
        const attempt: AuthValidationAttempt = {
          source: "publishable_get_user",
          ok: !!user && !error,
          status: error?.status ?? null,
          errorDetail: error?.message ?? (!user ? "user_without_id" : null),
        };
        validationAttempts.push(attempt);
        if (user && attempt.ok) {
          validatedUser = user;
          validationSource = attempt.source;
        }
      } catch (error) {
        validationAttempts.push({
          source: "publishable_get_user",
          ok: false,
          status: null,
          errorDetail: getSafeErrorDetail(error) ?? "get_user_failed",
        });
      }
    }

    if (!validatedUser && SUPABASE_PUBLISHABLE_KEY) {
      const restResult = await validateUserWithRest({
        source: "publishable_rest_user",
        supabaseUrl: SUPABASE_URL!,
        apiKey: SUPABASE_PUBLISHABLE_KEY,
        token,
      });
      validationAttempts.push(restResult.attempt);
      if (restResult.user) {
        validatedUser = restResult.user;
        validationSource = restResult.attempt.source;
      }
    }

    if (!validatedUser && SUPABASE_SERVICE_ROLE_KEY) {
      const restResult = await validateUserWithRest({
        source: "service_role_rest_user",
        supabaseUrl: SUPABASE_URL!,
        apiKey: SUPABASE_SERVICE_ROLE_KEY,
        token,
      });
      validationAttempts.push(restResult.attempt);
      if (restResult.user) {
        validatedUser = restResult.user;
        validationSource = restResult.attempt.source;
      }
    }

    const authDetail = getAuthAttemptHeaderValue(validationAttempts);

    if (!validatedUser?.id) {
      console.warn("[requireSupabaseAuth] auth diagnostic", {
        reason: "get_user_failed",
        ...authDiagnostics,
        authDetail,
        validationAttempts,
      });
      logUnauthorized("token_validation_failed", {
        ...authDiagnostics,
        authDetail,
        validationAttempts,
      });
      throw createUnauthorizedResponse(
        `Unauthorized: Supabase user validation failed${projectHost ? ` for ${projectHost}` : ""} [${authDetail}]`,
        "token_validation_failed",
        {
          projectHost,
          clientProjectHost,
          clientSessionPresent,
          clientAccessTokenPresent,
          tokenShape: tokenDiagnostics.headerValue,
          authDetail,
          validationSource: validationSource ?? "none",
        },
      );
    }

    if (validationSource !== "publishable_get_user") {
      console.warn("[requireSupabaseAuth] auth diagnostic", {
        reason:
          validationSource === "service_role_rest_user"
            ? "service_role_fallback_succeeded"
            : "publishable_rest_fallback_succeeded",
        ...authDiagnostics,
        validationSource,
        authDetail,
      });
    }

    let claimsData: { claims?: Record<string, unknown> | null } | null = null;
    let claimsErrorMessage: string | null = null;

    try {
      const { data, error } = await supabase.auth.getClaims(token);
      claimsData = data
        ? {
            claims:
              data.claims && typeof data.claims === "object"
                ? (data.claims as Record<string, unknown>)
                : null,
          }
        : null;
      claimsErrorMessage = error?.message ?? null;
    } catch (error) {
      claimsErrorMessage = error instanceof Error ? error.message : String(error);
    }

    const claimsSub = typeof claimsData?.claims?.sub === "string" ? claimsData.claims.sub : null;

    if (!claimsSub) {
      console.warn("[requireSupabaseAuth] auth diagnostic", {
        reason: "get_claims_failed",
        ...authDiagnostics,
        errorMessage: claimsErrorMessage,
        hasClaims: !!claimsData?.claims,
        hasSub: !!claimsSub,
      });
    }

    if (claimsSub && claimsSub !== validatedUser.id) {
      console.warn("[requireSupabaseAuth] auth diagnostic", {
        reason: "claims_sub_mismatch",
        ...authDiagnostics,
        claimsSub,
        userId: validatedUser.id,
      });
    }

    return next({
      context: createAuthContext({
        supabase,
        userId: validatedUser.id,
        email: validatedUser.email ?? null,
        claims: claimsData?.claims ?? null,
      }),
    });
  },
);
