// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function getSupabaseProjectHost(value: string | undefined) {
  if (!value) return null;

  try {
    return new URL(value).host;
  } catch (error) {
    console.error("[requireSupabaseAuth] invalid Supabase URL", {
      hasSupabaseUrl: true,
      error: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}

function logUnauthorized(reason: string, details: Record<string, unknown>) {
  console.error("[requireSupabaseAuth] unauthorized", {
    reason,
    ...details,
  });
}

function createUnauthorizedResponse(message: string, reason: string, projectHost: string | null) {
  return new Response(message, {
    status: 401,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "x-mgt-auth-reason": reason,
      "x-mgt-supabase-project-host": projectHost ?? "unknown",
    },
  });
}

function createAuthContext(input: {
  supabase: ReturnType<typeof createClient<Database>>;
  userId: string;
  email?: string | null;
}) {
  return {
    supabase: input.supabase,
    userId: input.userId,
    claims: {
      sub: input.userId,
      email: input.email ?? null,
    },
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;
    const projectHost = getSupabaseProjectHost(SUPABASE_URL);

    console.info("[requireSupabaseAuth] config", {
      hasSupabaseUrl: !!SUPABASE_URL,
      hasSupabasePublishableKey: !!SUPABASE_PUBLISHABLE_KEY,
      projectHost,
    });

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Response(message, { status: 500 });
    }

    const request = getRequest();

    if (!request?.headers) {
      logUnauthorized("no_request_headers", { projectHost });
      throw createUnauthorizedResponse(
        "Unauthorized: No request headers available",
        "no_request_headers",
        projectHost,
      );
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      logUnauthorized("no_authorization_header", { projectHost });
      throw createUnauthorizedResponse(
        "Unauthorized: No authorization header provided",
        "no_authorization_header",
        projectHost,
      );
    }

    if (!authHeader.startsWith("Bearer ")) {
      logUnauthorized("authorization_not_bearer", { projectHost });
      throw createUnauthorizedResponse(
        "Unauthorized: Only Bearer tokens are supported",
        "authorization_not_bearer",
        projectHost,
      );
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      logUnauthorized("no_token", { projectHost });
      throw createUnauthorizedResponse("Unauthorized: No token provided", "no_token", projectHost);
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (!error && data?.claims?.sub) {
      return next({
        context: createAuthContext({
          supabase,
          userId: data.claims.sub,
          email: typeof data.claims.email === "string" ? data.claims.email : null,
        }),
      });
    }

    console.warn("[requireSupabaseAuth] auth diagnostic", {
      reason: "get_claims_failed",
      projectHost,
      errorMessage: error?.message ?? null,
      hasClaims: !!data?.claims,
      hasSub: !!data?.claims?.sub,
    });

    const { data: userData, error: userError } = await supabase.auth.getUser(token);
    if (userError || !userData.user?.id) {
      console.warn("[requireSupabaseAuth] auth diagnostic", {
        reason: "get_user_failed",
        projectHost,
        errorMessage: userError?.message ?? null,
        hasUser: !!userData.user,
        hasUserId: !!userData.user?.id,
      });
      logUnauthorized("token_validation_failed", {
        projectHost,
        claimsErrorMessage: error?.message ?? null,
        hasClaims: !!data?.claims,
        hasClaimsSub: !!data?.claims?.sub,
        getUserErrorMessage: userError?.message ?? null,
        hasUser: !!userData.user,
        hasUserId: !!userData.user?.id,
      });
      throw createUnauthorizedResponse(
        `Unauthorized: Supabase token validation failed${projectHost ? ` for ${projectHost}` : ""}`,
        "token_validation_failed",
        projectHost,
      );
    }

    return next({
      context: createAuthContext({
        supabase,
        userId: userData.user.id,
        email: userData.user.email ?? null,
      }),
    });
  },
);
