// This file is automatically generated. Do not edit it directly.
// Regenerated from the MyGreekTax Portal Supabase project schema.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      accountants: {
        Row: {
          created_at: string;
          current_workload: number | null;
          email: string | null;
          id: string;
          name: string | null;
          notes: string | null;
          partner_progress_notes: string | null;
          phone: string | null;
          specialty: string | null;
          status: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          current_workload?: number | null;
          email?: string | null;
          id?: string;
          name?: string | null;
          notes?: string | null;
          partner_progress_notes?: string | null;
          phone?: string | null;
          specialty?: string | null;
          status?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          current_workload?: number | null;
          email?: string | null;
          id?: string;
          name?: string | null;
          notes?: string | null;
          partner_progress_notes?: string | null;
          phone?: string | null;
          specialty?: string | null;
          status?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      activity_events: {
        Row: {
          actor_email: string | null;
          actor_name: string | null;
          actor_user_id: string | null;
          event_type: string;
          id: string;
          metadata: Json;
          occurred_at: string;
          subject_label: string | null;
        };
        Insert: {
          actor_email?: string | null;
          actor_name?: string | null;
          actor_user_id?: string | null;
          event_type: string;
          id?: string;
          metadata?: Json;
          occurred_at?: string;
          subject_label?: string | null;
        };
        Update: {
          actor_email?: string | null;
          actor_name?: string | null;
          actor_user_id?: string | null;
          event_type?: string;
          id?: string;
          metadata?: Json;
          occurred_at?: string;
          subject_label?: string | null;
        };
        Relationships: [];
      };
      brain_ai_runs: {
        Row: {
          cache_creation_input_tokens: number | null;
          cache_read_input_tokens: number | null;
          completed_at: string | null;
          conversation_id: string;
          created_at: string;
          error_message: string | null;
          estimated_cost_usd: number | null;
          id: string;
          input_summary: Json;
          input_tokens: number | null;
          model: string;
          output: Json | null;
          output_tokens: number | null;
          prompt_version: string;
          provider: string;
          run_type: string;
          started_at: string | null;
          status: string;
          trigger_event_id: string | null;
        };
        Insert: {
          cache_creation_input_tokens?: number | null;
          cache_read_input_tokens?: number | null;
          completed_at?: string | null;
          conversation_id: string;
          created_at?: string;
          error_message?: string | null;
          estimated_cost_usd?: number | null;
          id?: string;
          input_summary?: Json;
          input_tokens?: number | null;
          model: string;
          output?: Json | null;
          output_tokens?: number | null;
          prompt_version: string;
          provider?: string;
          run_type: string;
          started_at?: string | null;
          status?: string;
          trigger_event_id?: string | null;
        };
        Update: {
          cache_creation_input_tokens?: number | null;
          cache_read_input_tokens?: number | null;
          completed_at?: string | null;
          conversation_id?: string;
          created_at?: string;
          error_message?: string | null;
          estimated_cost_usd?: number | null;
          id?: string;
          input_summary?: Json;
          input_tokens?: number | null;
          model?: string;
          output?: Json | null;
          output_tokens?: number | null;
          prompt_version?: string;
          provider?: string;
          run_type?: string;
          started_at?: string | null;
          status?: string;
          trigger_event_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "brain_ai_runs_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "brain_conversations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "brain_ai_runs_trigger_event_id_fkey";
            columns: ["trigger_event_id"];
            isOneToOne: false;
            referencedRelation: "brain_events";
            referencedColumns: ["id"];
          },
        ];
      };
      brain_approval_tasks: {
        Row: {
          assigned_to: string | null;
          conversation_id: string;
          created_at: string;
          draft_id: string | null;
          id: string;
          instructions: string | null;
          priority: string;
          resolved_at: string | null;
          resolved_by: string | null;
          status: string;
          task_type: string;
          title: string;
          updated_at: string;
        };
        Insert: {
          assigned_to?: string | null;
          conversation_id: string;
          created_at?: string;
          draft_id?: string | null;
          id?: string;
          instructions?: string | null;
          priority?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
          task_type?: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          assigned_to?: string | null;
          conversation_id?: string;
          created_at?: string;
          draft_id?: string | null;
          id?: string;
          instructions?: string | null;
          priority?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
          task_type?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "brain_approval_tasks_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "brain_conversations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "brain_approval_tasks_draft_id_fkey";
            columns: ["draft_id"];
            isOneToOne: false;
            referencedRelation: "brain_drafts";
            referencedColumns: ["id"];
          },
        ];
      };
      brain_conversations: {
        Row: {
          archived_at: string | null;
          case_number: number | null;
          case_serial_id: string | null;
          client_id: string | null;
          closed_at: string | null;
          conversation_type: string;
          created_at: string;
          customer_email: string;
          customer_id: string;
          id: string;
          job_id: string | null;
          lead_id: string | null;
          partner_email: string | null;
          partner_input_status: string;
          partner_required: boolean;
          stage: string;
          status: string;
          subject: string | null;
          updated_at: string;
        };
        Insert: {
          archived_at?: string | null;
          case_number?: number | null;
          case_serial_id?: string | null;
          client_id?: string | null;
          closed_at?: string | null;
          conversation_type?: string;
          created_at?: string;
          customer_email: string;
          customer_id: string;
          id?: string;
          job_id?: string | null;
          lead_id?: string | null;
          partner_email?: string | null;
          partner_input_status?: string;
          partner_required?: boolean;
          stage?: string;
          status?: string;
          subject?: string | null;
          updated_at?: string;
        };
        Update: {
          archived_at?: string | null;
          case_number?: number | null;
          case_serial_id?: string | null;
          client_id?: string | null;
          closed_at?: string | null;
          conversation_type?: string;
          created_at?: string;
          customer_email?: string;
          customer_id?: string;
          id?: string;
          job_id?: string | null;
          lead_id?: string | null;
          partner_email?: string | null;
          partner_input_status?: string;
          partner_required?: boolean;
          stage?: string;
          status?: string;
          subject?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "brain_conversations_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
        ];
      };
      brain_drafts: {
        Row: {
          ai_run_id: string | null;
          approved_at: string | null;
          approved_by: string | null;
          body_text: string;
          conversation_id: string;
          created_at: string;
          draft_type: string;
          edited_body_text: string | null;
          edited_subject: string | null;
          id: string;
          sent_at: string | null;
          sent_event_id: string | null;
          status: string;
          subject: string | null;
          updated_at: string;
        };
        Insert: {
          ai_run_id?: string | null;
          approved_at?: string | null;
          approved_by?: string | null;
          body_text: string;
          conversation_id: string;
          created_at?: string;
          draft_type: string;
          edited_body_text?: string | null;
          edited_subject?: string | null;
          id?: string;
          sent_at?: string | null;
          sent_event_id?: string | null;
          status?: string;
          subject?: string | null;
          updated_at?: string;
        };
        Update: {
          ai_run_id?: string | null;
          approved_at?: string | null;
          approved_by?: string | null;
          body_text?: string;
          conversation_id?: string;
          created_at?: string;
          draft_type?: string;
          edited_body_text?: string | null;
          edited_subject?: string | null;
          id?: string;
          sent_at?: string | null;
          sent_event_id?: string | null;
          status?: string;
          subject?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "brain_drafts_ai_run_id_fkey";
            columns: ["ai_run_id"];
            isOneToOne: false;
            referencedRelation: "brain_ai_runs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "brain_drafts_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "brain_conversations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "brain_drafts_sent_event_id_fkey";
            columns: ["sent_event_id"];
            isOneToOne: false;
            referencedRelation: "brain_events";
            referencedColumns: ["id"];
          },
        ];
      };
      brain_events: {
        Row: {
          actor: string;
          body_text: string | null;
          conversation_id: string;
          created_at: string;
          direction: string | null;
          email_references: string[];
          event_type: string;
          external_event_id: string;
          from_email: string | null;
          id: string;
          in_reply_to_message_id: string | null;
          metadata: Json;
          occurred_at: string;
          provider: string | null;
          provider_message_id: string | null;
          provider_thread_id: string | null;
          subject: string | null;
          to_emails: string[];
        };
        Insert: {
          actor: string;
          body_text?: string | null;
          conversation_id: string;
          created_at?: string;
          direction?: string | null;
          email_references?: string[];
          event_type: string;
          external_event_id: string;
          from_email?: string | null;
          id?: string;
          in_reply_to_message_id?: string | null;
          metadata?: Json;
          occurred_at?: string;
          provider?: string | null;
          provider_message_id?: string | null;
          provider_thread_id?: string | null;
          subject?: string | null;
          to_emails?: string[];
        };
        Update: {
          actor?: string;
          body_text?: string | null;
          conversation_id?: string;
          created_at?: string;
          direction?: string | null;
          email_references?: string[];
          event_type?: string;
          external_event_id?: string;
          from_email?: string | null;
          id?: string;
          in_reply_to_message_id?: string | null;
          metadata?: Json;
          occurred_at?: string;
          provider?: string | null;
          provider_message_id?: string | null;
          provider_thread_id?: string | null;
          subject?: string | null;
          to_emails?: string[];
        };
        Relationships: [
          {
            foreignKeyName: "brain_events_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "brain_conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      brain_states: {
        Row: {
          conversation_id: string;
          created_at: string;
          last_analysis_at: string | null;
          last_processed_event_id: string | null;
          state: Json;
          updated_at: string;
          version: number;
        };
        Insert: {
          conversation_id: string;
          created_at?: string;
          last_analysis_at?: string | null;
          last_processed_event_id?: string | null;
          state?: Json;
          updated_at?: string;
          version?: number;
        };
        Update: {
          conversation_id?: string;
          created_at?: string;
          last_analysis_at?: string | null;
          last_processed_event_id?: string | null;
          state?: Json;
          updated_at?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "brain_states_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: true;
            referencedRelation: "brain_conversations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "brain_states_last_processed_event_id_fkey";
            columns: ["last_processed_event_id"];
            isOneToOne: false;
            referencedRelation: "brain_events";
            referencedColumns: ["id"];
          },
        ];
      };
      case_draft_versions: {
        Row: {
          compliance_insights: string | null;
          context_used: Json;
          conversation_id: string;
          draft_text: string;
          generated_at: string;
          id: string;
          model: string | null;
          sent_at: string | null;
          sent_mode: string | null;
          sent_text: string | null;
          version_no: number;
        };
        Insert: {
          compliance_insights?: string | null;
          context_used?: Json;
          conversation_id: string;
          draft_text: string;
          generated_at?: string;
          id?: string;
          model?: string | null;
          sent_at?: string | null;
          sent_mode?: string | null;
          sent_text?: string | null;
          version_no: number;
        };
        Update: {
          compliance_insights?: string | null;
          context_used?: Json;
          conversation_id?: string;
          draft_text?: string;
          generated_at?: string;
          id?: string;
          model?: string | null;
          sent_at?: string | null;
          sent_mode?: string | null;
          sent_text?: string | null;
          version_no?: number;
        };
        Relationships: [
          {
            foreignKeyName: "case_draft_versions_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "brain_conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      case_drafts: {
        Row: {
          case_id: string;
          id: string;
          internal_notes: string | null;
          is_approved: boolean | null;
          last_updated: string | null;
          proposed_draft: string;
        };
        Insert: {
          case_id: string;
          id?: string;
          internal_notes?: string | null;
          is_approved?: boolean | null;
          last_updated?: string | null;
          proposed_draft: string;
        };
        Update: {
          case_id?: string;
          id?: string;
          internal_notes?: string | null;
          is_approved?: boolean | null;
          last_updated?: string | null;
          proposed_draft?: string;
        };
        Relationships: [];
      };
      case_notes: {
        Row: {
          author_user_id: string | null;
          body: string;
          conversation_id: string;
          created_at: string;
          id: string;
          include_in_ai: boolean;
          pinned: boolean;
          updated_at: string;
        };
        Insert: {
          author_user_id?: string | null;
          body: string;
          conversation_id: string;
          created_at?: string;
          id?: string;
          include_in_ai?: boolean;
          pinned?: boolean;
          updated_at?: string;
        };
        Update: {
          author_user_id?: string | null;
          body?: string;
          conversation_id?: string;
          created_at?: string;
          id?: string;
          include_in_ai?: boolean;
          pinned?: boolean;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "case_notes_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "brain_conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      case_summaries: {
        Row: {
          case_id: string;
          event_count: number | null;
          generated_at: string;
          summary: string;
        };
        Insert: {
          case_id: string;
          event_count?: number | null;
          generated_at?: string;
          summary: string;
        };
        Update: {
          case_id?: string;
          event_count?: number | null;
          generated_at?: string;
          summary?: string;
        };
        Relationships: [
          {
            foreignKeyName: "case_summaries_case_id_fkey";
            columns: ["case_id"];
            isOneToOne: true;
            referencedRelation: "brain_conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      case_timeline: {
        Row: {
          case_id: string;
          case_serial_id: string | null;
          created_at: string | null;
          event_type: string;
          id: string;
          payload: Json;
          sender: string;
          source_message_id: string | null;
        };
        Insert: {
          case_id: string;
          case_serial_id?: string | null;
          created_at?: string | null;
          event_type: string;
          id?: string;
          payload: Json;
          sender: string;
          source_message_id?: string | null;
        };
        Update: {
          case_id?: string;
          case_serial_id?: string | null;
          created_at?: string | null;
          event_type?: string;
          id?: string;
          payload?: Json;
          sender?: string;
          source_message_id?: string | null;
        };
        Relationships: [];
      };
      cases_directory: {
        Row: {
          case_serial_id: string;
          client_serial_id: string;
          created_at: string | null;
          id: string;
          status: string | null;
        };
        Insert: {
          case_serial_id: string;
          client_serial_id: string;
          created_at?: string | null;
          id?: string;
          status?: string | null;
        };
        Update: {
          case_serial_id?: string;
          client_serial_id?: string;
          created_at?: string | null;
          id?: string;
          status?: string | null;
        };
        Relationships: [];
      };
      client_token_events: {
        Row: {
          actor_email: string | null;
          actor_name: string | null;
          actor_user_id: string | null;
          event_type: string;
          id: string;
          metadata: Json;
          occurred_at: string;
          token: string;
        };
        Insert: {
          actor_email?: string | null;
          actor_name?: string | null;
          actor_user_id?: string | null;
          event_type: string;
          id?: string;
          metadata?: Json;
          occurred_at?: string;
          token: string;
        };
        Update: {
          actor_email?: string | null;
          actor_name?: string | null;
          actor_user_id?: string | null;
          event_type?: string;
          id?: string;
          metadata?: Json;
          occurred_at?: string;
          token?: string;
        };
        Relationships: [];
      };
      client_tokens: {
        Row: {
          airtable_client_id: string;
          airtable_job_id: string;
          client_email: string;
          created_at: string;
          created_by: string | null;
          expires_at: string;
          first_opened_at: string | null;
          last_country: string | null;
          last_ip: string | null;
          last_opened_at: string | null;
          last_user_agent: string | null;
          open_count: number;
          regenerated_from_token: string | null;
          revoked_at: string | null;
          token: string;
        };
        Insert: {
          airtable_client_id: string;
          airtable_job_id: string;
          client_email: string;
          created_at?: string;
          created_by?: string | null;
          expires_at: string;
          first_opened_at?: string | null;
          last_country?: string | null;
          last_ip?: string | null;
          last_opened_at?: string | null;
          last_user_agent?: string | null;
          open_count?: number;
          regenerated_from_token?: string | null;
          revoked_at?: string | null;
          token: string;
        };
        Update: {
          airtable_client_id?: string;
          airtable_job_id?: string;
          client_email?: string;
          created_at?: string;
          created_by?: string | null;
          expires_at?: string;
          first_opened_at?: string | null;
          last_country?: string | null;
          last_ip?: string | null;
          last_opened_at?: string | null;
          last_user_agent?: string | null;
          open_count?: number;
          regenerated_from_token?: string | null;
          revoked_at?: string | null;
          token?: string;
        };
        Relationships: [
          {
            foreignKeyName: "client_tokens_regenerated_from_token_fkey";
            columns: ["regenerated_from_token"];
            isOneToOne: false;
            referencedRelation: "client_tokens";
            referencedColumns: ["token"];
          },
        ];
      };
      clients: {
        Row: {
          afm: string | null;
          balance_due: number | null;
          cadence: string | null;
          case_code: string | null;
          client_code: string | null;
          client_visible_note: string | null;
          created_at: string;
          deposit: number | null;
          email: string | null;
          full_name: string | null;
          gmail_sent_last_sync: string | null;
          id: string;
          last_activity: string | null;
          lead_value: number | null;
          lost_reason: string | null;
          nationality: string | null;
          next_action: string | null;
          next_action_date: string | null;
          notes: string | null;
          parked_reason: string | null;
          partner_fee: number | null;
          phone: string | null;
          quote_amount: number | null;
          quote_sent_date: string | null;
          source: string | null;
          stage: string | null;
          status: string | null;
          taxisnet_access: boolean | null;
          thread_id: string | null;
          updated_at: string;
          urgency: string | null;
        };
        Insert: {
          afm?: string | null;
          balance_due?: number | null;
          cadence?: string | null;
          case_code?: string | null;
          client_code?: string | null;
          client_visible_note?: string | null;
          created_at?: string;
          deposit?: number | null;
          email?: string | null;
          full_name?: string | null;
          gmail_sent_last_sync?: string | null;
          id?: string;
          last_activity?: string | null;
          lead_value?: number | null;
          lost_reason?: string | null;
          nationality?: string | null;
          next_action?: string | null;
          next_action_date?: string | null;
          notes?: string | null;
          parked_reason?: string | null;
          partner_fee?: number | null;
          phone?: string | null;
          quote_amount?: number | null;
          quote_sent_date?: string | null;
          source?: string | null;
          stage?: string | null;
          status?: string | null;
          taxisnet_access?: boolean | null;
          thread_id?: string | null;
          updated_at?: string;
          urgency?: string | null;
        };
        Update: {
          afm?: string | null;
          balance_due?: number | null;
          cadence?: string | null;
          case_code?: string | null;
          client_code?: string | null;
          client_visible_note?: string | null;
          created_at?: string;
          deposit?: number | null;
          email?: string | null;
          full_name?: string | null;
          gmail_sent_last_sync?: string | null;
          id?: string;
          last_activity?: string | null;
          lead_value?: number | null;
          lost_reason?: string | null;
          nationality?: string | null;
          next_action?: string | null;
          next_action_date?: string | null;
          notes?: string | null;
          parked_reason?: string | null;
          partner_fee?: number | null;
          phone?: string | null;
          quote_amount?: number | null;
          quote_sent_date?: string | null;
          source?: string | null;
          stage?: string | null;
          status?: string | null;
          taxisnet_access?: boolean | null;
          thread_id?: string | null;
          updated_at?: string;
          urgency?: string | null;
        };
        Relationships: [];
      };
      email_send_log: {
        Row: {
          created_at: string;
          error_message: string | null;
          id: string;
          message_id: string | null;
          metadata: Json | null;
          recipient_email: string;
          status: string;
          template_name: string;
        };
        Insert: {
          created_at?: string;
          error_message?: string | null;
          id?: string;
          message_id?: string | null;
          metadata?: Json | null;
          recipient_email: string;
          status: string;
          template_name: string;
        };
        Update: {
          created_at?: string;
          error_message?: string | null;
          id?: string;
          message_id?: string | null;
          metadata?: Json | null;
          recipient_email?: string;
          status?: string;
          template_name?: string;
        };
        Relationships: [];
      };
      email_send_state: {
        Row: {
          auth_email_ttl_minutes: number;
          batch_size: number;
          id: number;
          retry_after_until: string | null;
          send_delay_ms: number;
          transactional_email_ttl_minutes: number;
          updated_at: string;
        };
        Insert: {
          auth_email_ttl_minutes?: number;
          batch_size?: number;
          id?: number;
          retry_after_until?: string | null;
          send_delay_ms?: number;
          transactional_email_ttl_minutes?: number;
          updated_at?: string;
        };
        Update: {
          auth_email_ttl_minutes?: number;
          batch_size?: number;
          id?: number;
          retry_after_until?: string | null;
          send_delay_ms?: number;
          transactional_email_ttl_minutes?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_unsubscribe_tokens: {
        Row: {
          created_at: string;
          email: string;
          id: string;
          token: string;
          used_at: string | null;
        };
        Insert: {
          created_at?: string;
          email: string;
          id?: string;
          token: string;
          used_at?: string | null;
        };
        Update: {
          created_at?: string;
          email?: string;
          id?: string;
          token?: string;
          used_at?: string | null;
        };
        Relationships: [];
      };
      job_change_requests: {
        Row: {
          airtable_job_id: string;
          created_at: string;
          current_value: string | null;
          decided_at: string | null;
          decided_by: string | null;
          decision_note: string | null;
          field_name: string;
          id: string;
          job_code: string | null;
          reason: string | null;
          requested_by: string;
          requested_value: string | null;
          requester_email: string | null;
          requester_name: string | null;
          status: string;
        };
        Insert: {
          airtable_job_id: string;
          created_at?: string;
          current_value?: string | null;
          decided_at?: string | null;
          decided_by?: string | null;
          decision_note?: string | null;
          field_name: string;
          id?: string;
          job_code?: string | null;
          reason?: string | null;
          requested_by: string;
          requested_value?: string | null;
          requester_email?: string | null;
          requester_name?: string | null;
          status?: string;
        };
        Update: {
          airtable_job_id?: string;
          created_at?: string;
          current_value?: string | null;
          decided_at?: string | null;
          decided_by?: string | null;
          decision_note?: string | null;
          field_name?: string;
          id?: string;
          job_code?: string | null;
          reason?: string | null;
          requested_by?: string;
          requested_value?: string | null;
          requester_email?: string | null;
          requester_name?: string | null;
          status?: string;
        };
        Relationships: [];
      };
      job_events: {
        Row: {
          actor_email: string | null;
          actor_name: string | null;
          airtable_job_id: string | null;
          comment: string | null;
          created_at: string;
          event_type: string;
          from_status: string | null;
          id: string;
          impersonated_accountant_id: string | null;
          to_status: string | null;
          user_id: string;
        };
        Insert: {
          actor_email?: string | null;
          actor_name?: string | null;
          airtable_job_id?: string | null;
          comment?: string | null;
          created_at?: string;
          event_type: string;
          from_status?: string | null;
          id?: string;
          impersonated_accountant_id?: string | null;
          to_status?: string | null;
          user_id: string;
        };
        Update: {
          actor_email?: string | null;
          actor_name?: string | null;
          airtable_job_id?: string | null;
          comment?: string | null;
          created_at?: string;
          event_type?: string;
          from_status?: string | null;
          id?: string;
          impersonated_accountant_id?: string | null;
          to_status?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      job_order_preferences: {
        Row: {
          created_at: string;
          id: string;
          ordered_job_ids: string[];
          scope_key: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          ordered_job_ids?: string[];
          scope_key: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          ordered_job_ids?: string[];
          scope_key?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      jobs: {
        Row: {
          accountant_fee: number | null;
          accountant_id: string | null;
          admin_internal_notes: string | null;
          client_fee: number | null;
          client_id: string | null;
          client_visible_note: string | null;
          created_at: string;
          date_sent: string | null;
          id: string;
          job_code: string | null;
          next_action_needed: string | null;
          notes: string | null;
          partner_progress_notes: string | null;
          service_id: string | null;
          sla_deadline: string | null;
          status: string | null;
          updated_at: string;
        };
        Insert: {
          accountant_fee?: number | null;
          accountant_id?: string | null;
          admin_internal_notes?: string | null;
          client_fee?: number | null;
          client_id?: string | null;
          client_visible_note?: string | null;
          created_at?: string;
          date_sent?: string | null;
          id?: string;
          job_code?: string | null;
          next_action_needed?: string | null;
          notes?: string | null;
          partner_progress_notes?: string | null;
          service_id?: string | null;
          sla_deadline?: string | null;
          status?: string | null;
          updated_at?: string;
        };
        Update: {
          accountant_fee?: number | null;
          accountant_id?: string | null;
          admin_internal_notes?: string | null;
          client_fee?: number | null;
          client_id?: string | null;
          client_visible_note?: string | null;
          created_at?: string;
          date_sent?: string | null;
          id?: string;
          job_code?: string | null;
          next_action_needed?: string | null;
          notes?: string | null;
          partner_progress_notes?: string | null;
          service_id?: string | null;
          sla_deadline?: string | null;
          status?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "jobs_accountant_id_fkey";
            columns: ["accountant_id"];
            isOneToOne: false;
            referencedRelation: "accountants";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "jobs_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "jobs_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "service_catalog";
            referencedColumns: ["id"];
          },
        ];
      };
      knowledge_base: {
        Row: {
          category: string | null;
          content: string;
          id: string;
          is_active: boolean | null;
          review_by: string | null;
          slug: string | null;
          source: string | null;
          status: string;
          tax_year: number | null;
          title: string;
          updated_at: string | null;
          visibility: string;
        };
        Insert: {
          category?: string | null;
          content: string;
          id?: string;
          is_active?: boolean | null;
          review_by?: string | null;
          slug?: string | null;
          source?: string | null;
          status?: string;
          tax_year?: number | null;
          title: string;
          updated_at?: string | null;
          visibility: string;
        };
        Update: {
          category?: string | null;
          content?: string;
          id?: string;
          is_active?: boolean | null;
          review_by?: string | null;
          slug?: string | null;
          source?: string | null;
          status?: string;
          tax_year?: number | null;
          title?: string;
          updated_at?: string | null;
          visibility?: string;
        };
        Relationships: [];
      };
      knowledge_candidates: {
        Row: {
          case_id: string | null;
          category: string | null;
          content: string;
          created_at: string;
          id: string;
          rationale: string | null;
          reviewed_at: string | null;
          status: string;
          title: string;
        };
        Insert: {
          case_id?: string | null;
          category?: string | null;
          content: string;
          created_at?: string;
          id?: string;
          rationale?: string | null;
          reviewed_at?: string | null;
          status?: string;
          title: string;
        };
        Update: {
          case_id?: string | null;
          category?: string | null;
          content?: string;
          created_at?: string;
          id?: string;
          rationale?: string | null;
          reviewed_at?: string | null;
          status?: string;
          title?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          airtable_id: string | null;
          body: string | null;
          client_id: string | null;
          created_at: string;
          direction: string | null;
          from_addr: string | null;
          id: string;
          message_id: string | null;
          subject: string | null;
          thread_id: string | null;
          to_addr: string | null;
          ts: string | null;
        };
        Insert: {
          airtable_id?: string | null;
          body?: string | null;
          client_id?: string | null;
          created_at?: string;
          direction?: string | null;
          from_addr?: string | null;
          id?: string;
          message_id?: string | null;
          subject?: string | null;
          thread_id?: string | null;
          to_addr?: string | null;
          ts?: string | null;
        };
        Update: {
          airtable_id?: string | null;
          body?: string | null;
          client_id?: string | null;
          created_at?: string;
          direction?: string | null;
          from_addr?: string | null;
          id?: string;
          message_id?: string | null;
          subject?: string | null;
          thread_id?: string | null;
          to_addr?: string | null;
          ts?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "messages_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
        ];
      };
      newsletter_subscribers: {
        Row: {
          client_id: string | null;
          confirmed_at: string | null;
          created_at: string;
          email: string;
          emailoctopus_id: string | null;
          full_name: string | null;
          id: string;
          last_synced_at: string | null;
          source: string | null;
          status: string;
          subscribed_at: string | null;
          tags: string[] | null;
          unsubscribed_at: string | null;
          updated_at: string;
        };
        Insert: {
          client_id?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
          email: string;
          emailoctopus_id?: string | null;
          full_name?: string | null;
          id?: string;
          last_synced_at?: string | null;
          source?: string | null;
          status?: string;
          subscribed_at?: string | null;
          tags?: string[] | null;
          unsubscribed_at?: string | null;
          updated_at?: string;
        };
        Update: {
          client_id?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
          email?: string;
          emailoctopus_id?: string | null;
          full_name?: string | null;
          id?: string;
          last_synced_at?: string | null;
          source?: string | null;
          status?: string;
          subscribed_at?: string | null;
          tags?: string[] | null;
          unsubscribed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "newsletter_subscribers_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
        ];
      };
      outbound_emails: {
        Row: {
          body: string | null;
          headers: Json | null;
          id: string;
          is_lead: boolean | null;
          message_id: string | null;
          recipient: string;
          sender: string;
          subject: string | null;
          timestamp: string | null;
        };
        Insert: {
          body?: string | null;
          headers?: Json | null;
          id?: string;
          is_lead?: boolean | null;
          message_id?: string | null;
          recipient: string;
          sender: string;
          subject?: string | null;
          timestamp?: string | null;
        };
        Update: {
          body?: string | null;
          headers?: Json | null;
          id?: string;
          is_lead?: boolean | null;
          message_id?: string | null;
          recipient?: string;
          sender?: string;
          subject?: string | null;
          timestamp?: string | null;
        };
        Relationships: [];
      };
      partner_invites: {
        Row: {
          airtable_accountant_id: string | null;
          consumed_at: string | null;
          consumed_user_id: string | null;
          created_at: string;
          created_by: string;
          email: string;
          expires_at: string;
          first_name: string;
          id: string;
          last_name: string;
          token_hash: string;
        };
        Insert: {
          airtable_accountant_id?: string | null;
          consumed_at?: string | null;
          consumed_user_id?: string | null;
          created_at?: string;
          created_by: string;
          email: string;
          expires_at?: string;
          first_name: string;
          id?: string;
          last_name: string;
          token_hash: string;
        };
        Update: {
          airtable_accountant_id?: string | null;
          consumed_at?: string | null;
          consumed_user_id?: string | null;
          created_at?: string;
          created_by?: string;
          email?: string;
          expires_at?: string;
          first_name?: string;
          id?: string;
          last_name?: string;
          token_hash?: string;
        };
        Relationships: [];
      };
      partner_profiles: {
        Row: {
          airtable_accountant_id: string;
          created_at: string;
          disabled_at: string | null;
          disabled_by: string | null;
          email: string;
          full_name: string | null;
          user_id: string;
        };
        Insert: {
          airtable_accountant_id: string;
          created_at?: string;
          disabled_at?: string | null;
          disabled_by?: string | null;
          email: string;
          full_name?: string | null;
          user_id: string;
        };
        Update: {
          airtable_accountant_id?: string;
          created_at?: string;
          disabled_at?: string | null;
          disabled_by?: string | null;
          email?: string;
          full_name?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      service_catalog: {
        Row: {
          airtable_id: string | null;
          base_client_price: number | null;
          category: string | null;
          created_at: string;
          id: string;
          notes: string | null;
          service_code: string | null;
          service_name: string | null;
          tier: string | null;
          updated_at: string;
        };
        Insert: {
          airtable_id?: string | null;
          base_client_price?: number | null;
          category?: string | null;
          created_at?: string;
          id?: string;
          notes?: string | null;
          service_code?: string | null;
          service_name?: string | null;
          tier?: string | null;
          updated_at?: string;
        };
        Update: {
          airtable_id?: string | null;
          base_client_price?: number | null;
          category?: string | null;
          created_at?: string;
          id?: string;
          notes?: string | null;
          service_code?: string | null;
          service_name?: string | null;
          tier?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      suppressed_emails: {
        Row: {
          created_at: string;
          email: string;
          id: string;
          metadata: Json | null;
          reason: string;
        };
        Insert: {
          created_at?: string;
          email: string;
          id?: string;
          metadata?: Json | null;
          reason: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          id?: string;
          metadata?: Json | null;
          reason?: string;
        };
        Relationships: [];
      };
      tracking_link_opens: {
        Row: {
          airtable_job_id: string | null;
          browser: string | null;
          city: string | null;
          client_email: string | null;
          country: string | null;
          device: string | null;
          id: string;
          ip: string | null;
          opened_at: string;
          os: string | null;
          referrer: string | null;
          token: string;
          user_agent: string | null;
        };
        Insert: {
          airtable_job_id?: string | null;
          browser?: string | null;
          city?: string | null;
          client_email?: string | null;
          country?: string | null;
          device?: string | null;
          id?: string;
          ip?: string | null;
          opened_at?: string;
          os?: string | null;
          referrer?: string | null;
          token: string;
          user_agent?: string | null;
        };
        Update: {
          airtable_job_id?: string | null;
          browser?: string | null;
          city?: string | null;
          client_email?: string | null;
          country?: string | null;
          device?: string | null;
          id?: string;
          ip?: string | null;
          opened_at?: string;
          os?: string | null;
          referrer?: string | null;
          token?: string;
          user_agent?: string | null;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          id: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Insert: {
          id?: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Update: {
          id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      jobs_expanded: {
        Row: {
          accountant_fee: number | null;
          accountant_id: string | null;
          admin_internal_notes: string | null;
          base_client_price: number | null;
          category: string | null;
          client_code: string | null;
          client_fee: number | null;
          client_full_name: string | null;
          client_id: string | null;
          client_visible_note: string | null;
          created_at: string | null;
          date_sent: string | null;
          id: string | null;
          job_code: string | null;
          margin: number | null;
          next_action_needed: string | null;
          notes: string | null;
          partner_progress_notes: string | null;
          service_code: string | null;
          service_id: string | null;
          service_name: string | null;
          sla_deadline: string | null;
          status: string | null;
          tier: string | null;
          updated_at: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "jobs_accountant_id_fkey";
            columns: ["accountant_id"];
            isOneToOne: false;
            referencedRelation: "accountants";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "jobs_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "jobs_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "service_catalog";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Functions: {
      archive_case: { Args: { p_conversation_id: string }; Returns: undefined };
      delete_case: { Args: { p_conversation_id: string }; Returns: undefined };
      delete_email: {
        Args: { message_id: number; queue_name: string };
        Returns: boolean;
      };
      enqueue_email: {
        Args: { payload: Json; queue_name: string };
        Returns: number;
      };
      get_partner_last_seen: {
        Args: { _user_ids: string[] };
        Returns: {
          last_seen_at: string;
          user_id: string;
        }[];
      };
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"];
          _user_id: string;
        };
        Returns: boolean;
      };
      is_my_partner_profile: { Args: { _user_id: string }; Returns: boolean };
      lookup_case_uuid_by_serial: {
        Args: { search_serial: string };
        Returns: string;
      };
      mgt_ops_snapshot: { Args: never; Returns: Json };
      move_to_dlq: {
        Args: {
          dlq_name: string;
          message_id: number;
          payload: Json;
          source_queue: string;
        };
        Returns: number;
      };
      purge_expired_archived_cases: { Args: never; Returns: number };
      read_email_batch: {
        Args: { batch_size: number; queue_name: string; vt: number };
        Returns: {
          message: Json;
          msg_id: number;
          read_ct: number;
        }[];
      };
      resolve_case_for_inbound:
        | {
            Args: { p_email: string; p_name?: string; p_nationality?: string };
            Returns: {
              out_case_number: number;
              out_case_serial_id: string;
              out_client_code: string;
              out_client_id: string;
              out_is_new_case: boolean;
              out_is_new_customer: boolean;
            }[];
          }
        | {
            Args: {
              p_email: string;
              p_external_event_id?: string;
              p_message?: string;
              p_name?: string;
              p_nationality?: string;
              p_provider?: string;
              p_subject?: string;
            };
            Returns: {
              out_case_number: number;
              out_case_serial_id: string;
              out_client_code: string;
              out_client_id: string;
              out_conversation_id: string;
              out_is_new_case: boolean;
              out_is_new_customer: boolean;
            }[];
          };
      restore_case: { Args: { p_conversation_id: string }; Returns: undefined };
    };
    Enums: {
      app_role: "admin" | "partner";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      app_role: ["admin", "partner"],
    },
  },
} as const;
